name: Validate Java e2e

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  java-action-test:
    runs-on: ubuntu-22.04-ppc64le
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Temurin java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: 'ppc64le'
      - run: |
          java -version
      - name: Sleep for 150 seconds
        run: sleep 150s
