name: Basic validation

on:
  workflow_dispatch:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  java-action-test:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - uses: actions/checkout@v3
      - name: Setup Adopt java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          architecture: 'ppc64le'
          check-latest: true
      - run: |
          java -version
